# Generated by Django 4.1 on 2022-08-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blogTitle", models.CharField(max_length=300)),
                ("blogBody", models.CharField(max_length=1000)),
            ],
        ),
    ]
